import Head from 'next/head';
import { useRouter } from 'next/router';
import { AuthContext } from "@/contexts/AuthContext";
import {useContext, useEffect} from 'react';
import DashboardContent from '@/contents/DashboardContent';
import HeaderAftLogin from '@/components/Header/HeaderAftLogin';
import Footer from '@/components/Footer/Footer';
import Polygon from '@/components/Polygon/Polygon';

export default function Dashboard() {
  const authContext = useContext(AuthContext);
  const router = useRouter()

  useEffect(() => {
    if (localStorage.getItem("token") != undefined && localStorage.getItem("user") !=  undefined) {
      authContext.setAuthState({
        token:localStorage.getItem("token"),
        user:localStorage.getItem("user")
      })
    }

    if (!authContext.isUserAuthenticated()) {
      router.push("/login")
    } 
  }, [])


  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Polygon />
      <HeaderAftLogin />
      <div className='d-flex align-items-center justify-content-center' style={{marginBottom: '10vw'}}>
      <DashboardContent >Dashboard {authContext.authState.user}</DashboardContent>
      </div>
      <Footer />
    </>
  );
}