import Head from 'next/head';
import { useRouter } from 'next/router';
import { AuthContext } from "@/contexts/AuthContext";
import {useContext, useEffect} from 'react';
import DashboardContent from '@/contents/DashboardContent';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import Polygon from '@/components/Polygon/Polygon';
import Category from '@/components/Category/Category';
import LastPosts from '@/components/LastPosts/LastPosts';
import PostType from '@/components/LastPosts/PostType';
import UserTab from '@/components/UserTab/UserTab';
import ImageUser from '../../public/images/perfil.png';

export default function Dashboard() {
  const authContext = useContext(AuthContext);
  const router = useRouter()

  useEffect(() => {
    if (localStorage.getItem("token") != undefined && localStorage.getItem("user") !=  undefined) {
      authContext.setAuthState({
        token:localStorage.getItem("token"),
        user:localStorage.getItem("user")
      })
    }

    if (!authContext.isUserAuthenticated()) {
      router.push("/login")
    } 
  }, [])

  const HandleLogOut = () => {
    console.log("log out");
  }

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Polygon />
      <Header logged={true}>
        <UserTab name={authContext.authState.user} image={ImageUser} HandleLogOut={HandleLogOut}/>
      </Header>
      <DashboardContent>
          <Category/>
          <LastPosts>
            <PostType 
              textButton={"Procurando alguém para dividir apartamento no endereço"}
              category={"books"}
              />
          </LastPosts>
      </DashboardContent>
      <Footer />
    </>
  );
}