import Head from 'next/head';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import HomeContent from '@/contents/HomeContent';
import Polygon from '@/components/Polygon/Polygon';

export default function Home() {
  return (
    <>
      <Head>
        <title>Facilitaí</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Polygon/>
      <Header/>
      <HomeContent/>
      <Footer/>
    </>
  )
}