import Head from 'next/head';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import LoginContent from '@/contents/LoginContent';
import Polygon from '@/components/Polygon/Polygon';

export default function Login() {
    return (
        <>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Polygon/>
            <Header />
            <LoginContent/>
            <Footer />
        </>
    )
}