import Head from 'next/head';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import LoginContent from '@/contents/LoginContent';
import Polygon from '@/components/Polygon/Polygon';
import Form from '@/components/Form/Form';
import SignUpForm from '@/components/SignUpForm/SignUpForm';
import React from 'react'

export default function Login() {

    const [form, setForm] = React.useState(true)

    const ChangeForm = () => {
        setForm(!form)
    }

    return (
        <>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Polygon />
            <Header />
            <LoginContent>
                {
                    form ? <Form ChangeForm={ChangeForm}/> : <SignUpForm ChangeForm={ChangeForm}/>
                }
            </LoginContent>
            <Footer />
        </>
    )
}