import Head from 'next/head';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import Polygon from '@/components/Polygon/Polygon';
import CreatePostContent from '@/contents/CreatePostContent';
import React from "react"

export default function NewPosts() {
    return (
        <>
            <Head>
                <title>Novo Anúncio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Polygon/>
            <Header />
            <CreatePostContent/>
            <Footer />
        </>
    )
}