import Head from 'next/head';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import PostsContent from '@/contents/PostsContent';
import Polygon from '@/components/Polygon/Polygon';
import React from "react"

export default function Posts() {
    return (
        <div className="d-flex flex-column justify-content-center align-items-center min-vh-100">
            <Head>
                <title>Anúncios</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Polygon/>
            <Header />
            <PostsContent/>
            <Footer />
        </div>
    )
}